# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: tobiagbola@gmail.com
author_name: Tobi
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: plotly-extension
mimetype: ''
mimetype_name: ''
project_short_description: Extension for plotly technical test
python_name: plotly_extension
repository: https://github.com/agbolatobi/plotly-extension.git
test: true
viewer_name: ''

